// TO DO
// CREATE ADD USER PROMPT TO CONVOS UTIL Fn.
// TAKE CARE IN CASE ITS A FIRST CONVO ACEPT PARAMENTER NEW: TRUE | FALSE
// CREATE ADD AI response TO CONVOS UTIL fn.
// BOTH IN SAME FILE SAVECONVO.TS
// IN SERVICES DEFINE PROVIDERS AND API CHECKERS
// IN HERE CALL SPECIFIC PROVIDER DEPENDING ON PROVIDER:string
// RETURN AI GENERATED RESPONSE
